-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color10 = '#0f0b14'
local Color5 = '#9898a6'
local Color6 = '#000000'
local Color11 = '#130b11'
local Color3 = '#c58fff'
local Color2 = '#ffbb88'
local Color12 = '#131217'
local Color13 = '#0000'
local Color1 = '#8eb6f5'
local Color0 = '#43444D'
local Color9 = '#0a090c'
local Color4 = '#f58ee0'
local Color7 = '#575861'
local Color8 = '#868690'

highlight('Comment', nil, Color0, 'italic')
highlight('Constant', nil, Color1, nil)
highlight('Number', nil, Color2, nil)
highlight('Type', nil, Color3, nil)
highlight('Error', nil, Color4, nil)
highlight('Keyword', nil, Color1, nil)
highlight('String', nil, Color5, nil)
highlight('Identifier', nil, Color2, 'italic')
highlight('StatusLine', Color7, Color6, nil)
highlight('WildMenu', Color6, Color8, nil)
highlight('Pmenu', Color6, Color8, nil)
highlight('PmenuSel', Color8, Color9, nil)
highlight('PmenuThumb', Color6, Color8, nil)
highlight('DiffAdd', Color10, nil, nil)
highlight('DiffDelete', Color11, nil, nil)
highlight('Normal', Color6, Color8, nil)
highlight('Visual', Color12, nil, nil)
highlight('CursorLine', Color12, nil, nil)
highlight('ColorColumn', Color12, nil, nil)
highlight('SignColumn', Color6, nil, nil)
highlight('LineNr', nil, Color7, nil)
highlight('TabLine', Color13, Color7, nil)
highlight('TabLineSel', Color8, Color9, nil)
highlight('TabLineFill', Color13, Color7, nil)
highlight('TSPunctDelimiter', nil, Color8, nil)

link('TSComment', 'Comment')
link('TSString', 'String')
link('TSType', 'Type')
link('Operator', 'Keyword')
link('TSFunction', 'Function')
link('TelescopeNormal', 'Normal')
link('TSNumber', 'Number')
link('TSTag', 'MyTag')
link('CursorLineNr', 'Identifier')
link('TSConditional', 'Conditional')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSLabel', 'Type')
link('TSConstant', 'Constant')
link('TSField', 'Constant')
link('TSOperator', 'Operator')
link('TSParameterReference', 'TSParameter')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSTagDelimiter', 'Type')
link('NonText', 'Comment')
link('Whitespace', 'Comment')
link('TSNamespace', 'TSType')
link('TSParameter', 'Constant')
link('TSKeyword', 'Keyword')
link('TSProperty', 'TSField')
link('Macro', 'Function')
link('TSPunctBracket', 'MyTag')
link('TSRepeat', 'Repeat')
link('Conditional', 'Operator')
link('TSFuncMacro', 'Macro')
link('Repeat', 'Conditional')
link('TSFloat', 'Number')
link('Folded', 'Comment')
